# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /bower_components
  static_dir: build/es6-bundled/bower_components
  secure: always

- url: /images
  static_dir: build/es6-bundled/images
  secure: always

- url: /src
  static_dir: build/es6-bundled/src
  secure: always

- url: /service-worker.js
  static_files: build/es6-bundled/service-worker.js
  upload: build/es6-bundled/service-worker.js
  secure: always

- url: /manifest.json
  static_files: build/es6-bundled/manifest.json
  upload: build/es6-bundled/manifest.json
  secure: always

- url: /.*
  static_files: build/es6-bundled/index.html
  upload: build/es6-bundled/index.html
  secure: always
# [END handlers]
